openapi: "3.0.3"
info:
  title: "Jibacco APIs"
  description: "backend APIs handling frontend requests via nginx"
  version: "0.0.1"
externalDocs:
  description: "GitHub Repository"
  url: "https://github.com/krtsato/jibacco"
servers:
  - url: "http://localhost:3000/main-api/v1"
    description: "Development main API server"
tags:
  - name: "user"
    description: "API for user"
paths:
  /users:
    get:
      tags:
        - "user"
      summary: "Get All users"
      responses:
        200:
          description: "Returns an array of User model"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                      format: "int64"
                    name:
                      type: "string"
                  required:
                    - "id"
                    - "name"
              examples:
                users:
                  value:
                    - id: 1
                      name: "涼宮ハルヒ"
                    - id: 2
                      name: "Haruhi Suzumiya"
components:
  responses:
    users:
      description: "Returns an array of User model"
      content:
        application/json:
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  format: "int64"
                name:
                  type: "string"
              required:
                - "id"
                - "name"
          examples:
            users:
              value:
                - id: 1
                  name: "涼宮ハルヒ"
                - id: 2
                  name: "Haruhi Suzumiya"
  schemas:
    user:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
      required:
        - "id"
        - "name"
  examples:
    users:
      value:
        - id: 1
          name: "涼宮ハルヒ"
        - id: 2
          name: "Haruhi Suzumiya"
